image: docker

stages:
  - build
  - push

variables:
  IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_dev:
  stage: build
  tags:
    - docker
  except:
    - master
   
  script:
    - docker build --build-arg script=build -t $IMAGE .

build_prod:
  stage: build
  tags:
    - docker
  only:
    - master
 
  script:
    - docker build --build-arg script=build:prod -t $IMAGE .

push:
  stage: push
  tags:
    - docker
  only:
    - develop
    - master
 
  script:
    - docker push $IMAGE

